model_name_or_path: "../result/TwoStageCoT-BERT"
output_dir: "../result/TwoStageCoT-BERT-eval"
do_eval: true
do_train: false
fp16: false
use_mps_device: false
seed: 0

# Evaluation settings
task_set: sts
mode: test

# TwoStageCoT specific arguments
temperature: 0.05

# Template arguments (与训练时保持一致)
mask_embedding_sentence: true
stage1_negative_template: "The sentence of \"[X]\" doesn't mean [MASK]."
stage1_anchor_template: "The sentence of \"[X]\" means [MASK]."
stage1_positive_template: "The sentence : \"[X]\" means [MASK]."
stage2_template: "so the sentence's meaning of \"[IT_SPECIAL_TOKEN]\" can be summarized as [MASK]."

