model_name_or_path: "../result/TwoStageCoT-BERT"
output_dir: "../result/TwoStageCoT-BERT-eval"
do_eval: true
do_train: false
fp16: false
use_mps_device: true
seed: 0

# Evaluation settings
task_set: sts
mode: test

# TwoStageCoT specific arguments
temperature: 0.05

# Template arguments (与训练时保持一致)
mask_embedding_sentence: true
stage1_template: "The sentence of \"[X]\" means [MASK]."
stage2_template: "so [it] can be summarized as [MASK]."

