model_name_or_path: "../result/PrismDecomp-BERT"
output_dir: "../result/PrismDecomp-BERT-eval"
do_eval: true
do_train: false
fp16: false
use_mps_device: true
seed: 0

# Evaluation settings
task_set: sts
mode: test

# PrismDecomp specific arguments
num_semantics: 7
orthogonal_constraint: true
semantic_weights_learnable: true

